spring:
  application:
    name: fintrack

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fintrack}
    username: ${DB_USER:fintrack_user}
    password: ${DB_PASS:fintrack_pass}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      username: ${SPRING_DATA_REDIS_USERNAME:}
      password: ${SPRING_DATA_REDIS_PASSWORD:}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:change-this-secret-key-change-this-secret-key-1234567890}
  expiration: 86400000

server:
  port: ${PORT:8080}

app:
  cors:
    allowed-origins: ${APP_CORS_ORIGINS:http://localhost:5173}

springdoc:
  swagger-ui:
    path: /swagger-ui.html