spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/fintrack}
    username: ${DB_USER:fintrack_user}
    password: ${DB_PASS:fintrack_pass}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      username: ${SPRING_DATA_REDIS_USERNAME:}
      password: ${SPRING_DATA_REDIS_PASSWORD:}


  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET:change-this-secret-key-change-this-secret-key-1234567890}

app:
  cors:
    allowed-origins: ${APP_CORS_ORIGINS:http://localhost:5173}
